### ISSUE TITLE
Help! Gearbox is creating Script Errors

### ISSUE THREAD

**Issue by sukablyatrushB** [nrlulz/ACF#298] opened 2019-01-05 08:13 UTC
I followed tutorials on how to make a basic car in ACF and I have done everything but everytime I enter my seat I get Script Errors

**Comment by Jophes** [comment] 2019-01-05 11:34
We'll need to know what the console errors are, otherwise we can't do anything.

**Comment by sukablyatrushB** [comment] 2019-01-05 12:45
this is one

[ERROR] addons/acf-master/lua/entities/acf_gearbox.lua:911: attempt to call method 'ApplyTorqueCenter' (a nil value)
  1. ActWheel - addons/acf-master/lua/entities/acf_gearbox.lua:911
   2. Act - addons/acf-master/lua/entities/acf_gearbox.lua:878
    3. CalcRPM - addons/acf-master/lua/entities/acf_engine.lua:598
     4. unknown - addons/acf-master/lua/entities/acf_engine.lua:426

**Comment by thegrb93** [comment] 2019-01-05 21:53
Your server/game needs to be updated

**Comment by sukablyatrushB** [comment] 2019-01-05 22:21
I have GMod 16 is that enough?

**Comment by thegrb93** [comment] 2019-01-05 22:36
Duplicate of https://github.com/nrlulz/ACF/issues/279

**Comment by sukablyatrushB** [comment] 2019-01-06 01:40
I ran the command and I got 160424

**Closed** 2019-01-30 07:40 UTC
